const app=document.getElementById('app');let state=GM_STORE.load();let route='home';let activeMatch=null;let selectedTeamIndex=0;
const t=k=>(GM_I18N[state.lang]&&GM_I18N[state.lang][k])||GM_I18N.de[k]||k;const flag=c=>GM_DATA.flags[c]||'🏳️';
function init(){initLang();bindMenu();applyI18n();render();GM_AUTOSAVE.now();GM_AUTOSAVE.install();}
function initLang(){const sel=document.getElementById('languageSelect');sel.innerHTML=Object.keys(GM_I18N).map(k=>`<option value="${k}">${GM_I18N[k].name}</option>`).join('');sel.value=state.lang;sel.onchange=()=>{state.lang=sel.value;GM_STORE.save(state);applyI18n();render();};}
function bindMenu(){document.getElementById('menuBtn').onclick=()=>openMenu(true);document.getElementById('closeMenu').onclick=()=>openMenu(false);document.getElementById('overlay').onclick=()=>openMenu(false);document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));document.body.addEventListener('click',GM_SOUNDS.unlock,{once:true});}
function openMenu(v){document.getElementById('drawer').classList.toggle('open',v);document.getElementById('overlay').classList.toggle('open',v);}
function applyI18n(){document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.documentElement.lang=state.lang;document.body.dir=state.lang==='ar'?'rtl':'ltr';}
function go(r){GM_AUTOSAVE.now();route=r;openMenu(false);activeMatch=null;render();GM_AUTOSAVE.schedule();scrollTo(0,0);}
function currentLeague(){return state.leagues[state.country][state.leagueIndex];}
function htmlPage(title,content,extra=''){app.innerHTML=`<div class="pageNavFixed"><button class="gold" onclick="go('home')">⬅ ${t('back')}</button><button onclick="openMenu(true)">☰ ${t('menu')}</button></div><section class="card infoPage"><div class="toolbar pageToolbar"><button class="gold" onclick="go('home')">⬅ ${t('back')}</button><button onclick="openMenu(true)">☰ ${t('menu')}</button></div><h1>${title}</h1>${content}${extra}</section>`;applyI18n();}
function render(){applyI18n(); if(route==='home')return renderHome(); if(route==='countries')return renderCountries(); if(route==='leagues')return renderLeagues(); if(route==='columns')return renderColumns(); if(route==='fixtures')return renderFixtures(); if(route==='play')return renderPlay(); if(route==='champions')return renderSimpleCup('champions'); if(route==='worldcup')return renderSimpleCup('worldcup'); if(route==='season')return renderSeason(); if(route==='records')return renderRecords(); if(route==='privacy')return htmlPage('🔒 '+t('privacy'),`<div class="card legalText">${esc(t('privacyText'))}</div>`); if(route==='terms')return htmlPage('📜 '+t('terms'),`<div class="card legalText">${esc(t('termsText'))}</div>`); if(route==='guide')return htmlPage('📖 '+t('guide'),`<div class="card legalText">${esc(t('guideText'))}</div>`); if(route==='help')return htmlPage('❓ '+t('help'),`<div class="card legalText">${esc(t('helpText'))}</div>`);}
function renderHome(){app.innerHTML=`<section class="card"><h1>⚽ GOALMONDO World V6.2.2 Stable</h1><p class="small">${t('welcome')}</p><div class="grid menuGrid">${[['countries','🌍','chooseCountry'],['leagues','🏆','manageLeagues'],['columns','🎲','playerColumns'],['fixtures','📅','fixtures'],['champions','⭐','champions'],['worldcup','🌍','worldcup'],['season','💾','seasonManager'],['records','🥇','records'],['guide','📖','guide'],['help','❓','help'],['privacy','🔒','privacy']].map(x=>`<button onclick="go('${x[0]}')">${x[1]} ${t(x[2])}</button>`).join('')}</div></section><section class="card saveBox"><h2>💾 ${t('save')}</h2><button class="gold" onclick="manualSave()">💾 ${t('saveNow')}</button><br><br><button onclick="restoreBackup()">♻️ ${t('restoreBackup')}</button><p class="small">${t('rebuild')}</p></section>`;}
function renderCountries(){app.innerHTML=`<section class="card"><h1>🌍 ${t('chooseCountry')}</h1><div class="grid">${GM_DATA.countries.map(c=>`<button class="country ${state.country===c?'active':''}" onclick="state.country='${c}';state.leagueIndex=0;GM_STORE.save(state);go('leagues')">${flag(c)} ${c}</button>`).join('')}</div></section>`;}
function renderLeagues(){const leagues=state.leagues[state.country];app.innerHTML=`<section class="card"><h1>🏆 ${flag(state.country)} ${state.country}</h1><div class="list">${leagues.map((l,i)=>`<div class="row"><button class="${i===state.leagueIndex?'gold':''}" onclick="state.leagueIndex=${i};GM_STORE.save(state);renderLeagues()">${l.name}</button><button onclick="removeLeague(${i})">🗑️</button></div>`).join('')}</div><div class="card"><h2>${t('team')}</h2><div class="toolbar"><input id="newTeam" placeholder="${t('team')}"><button onclick="addTeam()">➕ ${t('add')}</button></div><div class="list">${currentLeague().teams.map((tm,i)=>`<div class="row"><span>${i+1}. ${tm.name} <span class="tag">${tm.numbers.length}/16</span></span><button onclick="removeTeam(${i})">${t('remove')}</button></div>`).join('')||t('noTeams')}</div></div><button class="gold" onclick="addLeague()">➕ ${t('add')} ${t('league')}</button></section>`;}
function addLeague(){state.leagues[state.country].push({name:`${state.leagues[state.country].length+1}. Liga`,teams:[],fixtures:[]});state.leagueIndex=state.leagues[state.country].length-1;GM_STORE.save(state);renderLeagues();}
function removeLeague(i){if(state.leagues[state.country].length<=1)return;state.leagues[state.country].splice(i,1);state.leagueIndex=0;GM_STORE.save(state);renderLeagues();}
function addTeam(){const v=document.getElementById('newTeam').value.trim();if(!v)return;const l=currentLeague();if(l.teams.length>=20)return alert('Max 20');l.teams.push({name:v,numbers:[],stats:{p:0,w:0,d:0,l:0,gf:0,ga:0},played:{}});l.fixtures=[];GM_STORE.save(state);renderLeagues();}
function removeTeam(i){const l=currentLeague();if((l.teams[i].numbers||[]).length>=16)return alert(t('locked'));l.teams.splice(i,1);l.fixtures=[];GM_STORE.save(state);renderLeagues();}
function renderColumns(){const l=currentLeague();if(!l.teams.length){app.innerHTML=`<section class="card"><h1>🎲 ${t('playerColumns')}</h1><p class="small">${t('noTeams')}</p><div class="toolbar"><input id="colNewTeam" placeholder="${t('team')}"><button onclick="addTeamFromColumns()">➕ ${t('add')}</button></div></section>`;return;}if(selectedTeamIndex<0||selectedTeamIndex>=l.teams.length)selectedTeamIndex=0;app.innerHTML=`<section class="card"><h1>🎲 ${t('playerColumns')}</h1><div class="toolbar"><select id="teamPick" onchange="selectedTeamIndex=Number(this.value);drawNumbers(selectedTeamIndex)">${l.teams.map((tm,i)=>`<option value="${i}" ${i===selectedTeamIndex?'selected':''}>${tm.name}</option>`).join('')}</select><button class="gold" onclick="rollAll()">🎲 ${t('rollAll')}</button></div><div class="toolbar"><input id="colNewTeam" placeholder="${t('team')}"><button onclick="addTeamFromColumns()">➕ ${t('add')}</button></div><div class="teamTabs">${l.teams.map((tm,i)=>`<button class="mini ${i===selectedTeamIndex?'gold':''}" onclick="selectedTeamIndex=${i};drawNumbers(${i})">${i+1}. ${tm.name} <span class="tag">${tm.numbers.length}/16</span></button>`).join('')}</div><div id="numArea"></div></section>`;drawNumbers(selectedTeamIndex);}
function addTeamFromColumns(){const input=document.getElementById('colNewTeam');const v=(input&&input.value||'').trim();if(!v)return;const l=currentLeague();if(l.teams.length>=20)return alert('Max 20');l.teams.push({name:v,numbers:[],stats:{p:0,w:0,d:0,l:0,gf:0,ga:0},played:{}});l.fixtures=[];selectedTeamIndex=l.teams.length-1;GM_STORE.save(state);renderColumns();}
function drawNumbers(idx){const l=currentLeague();const tm=l.teams[idx];if(!tm)return;selectedTeamIndex=idx;const slots=Array.from({length:16},(_,i)=>{const val=tm.numbers[i]||'';const disabled=tm.numbers.length>=16?'disabled':'';return `<input class="numInput" type="number" min="1" max="20" value="${val}" placeholder="${i+1}" ${disabled} onchange="setManualNumber(${idx},${i},this.value)">`;}).join('');const area=document.getElementById('numArea');if(!area)return;area.innerHTML=`<h2>${tm.name} <span class="tag">${tm.numbers.length}/16</span></h2><div class="numbers fixed16">${slots}</div><br><div class="toolbar"><button onclick="rollOne(${idx})" ${tm.numbers.length>=16?'disabled':''}>🎲 ${t('roll')}</button><button class="gold" onclick="rollAll()" ${tm.numbers.length>=16?'disabled':''}>🎲 ${t('rollAll')}</button><button onclick="clearNumbers(${idx})">↺ ${t('remove')}</button></div>${tm.numbers.length>=16?`<p class="ok">${t('locked')}</p>`:''}`;const pick=document.getElementById('teamPick');if(pick)pick.value=idx;}
function setManualNumber(idx,pos,value){const tm=currentLeague().teams[idx];if(!tm)return;if(tm.numbers.length>=16)return drawNumbers(idx);let n=Number(value);if(!Number.isInteger(n)||n<1||n>20)return drawNumbers(idx);const old=tm.numbers[pos];if(tm.numbers.some((x,i)=>x===n&&i!==pos)){alert('Diese Zahl gibt es schon.');return drawNumbers(idx);}tm.numbers[pos]=n;tm.numbers=tm.numbers.filter(x=>Number.isInteger(x)&&x>=1&&x<=20);GM_STORE.save(state);drawNumbers(idx);}
function clearNumbers(idx){const tm=currentLeague().teams[idx];if(!tm)return;if(!confirm(`${tm.name}: 16 Zahlen löschen?`))return;tm.numbers=[];GM_STORE.save(state);drawNumbers(idx);}
function rollOne(idx){const tm=currentLeague().teams[idx];if(!tm||tm.numbers.length>=16)return;let n;let guard=0;do{n=Math.floor(Math.random()*20)+1;guard++;}while(tm.numbers.includes(n)&&guard<100);if(!tm.numbers.includes(n))tm.numbers.push(n);GM_STORE.save(state);drawNumbers(idx);}
function rollAll(){const idx=selectedTeamIndex;const tm=currentLeague().teams[idx];if(!tm)return;while(tm.numbers.length<16)rollOne(idx);GM_STORE.save(state);drawNumbers(idx);}
function makeFixtures(){const l=currentLeague();const games=[];for(let i=0;i<l.teams.length;i++){for(let j=i+1;j<l.teams.length;j++){games.push({h:i,a:j,played:false,hg:null,ag:null});}}if(state.mode==='double'){const first=[...games];games.push(...first.map(g=>({h:g.a,a:g.h,played:false,hg:null,ag:null})));}l.fixtures=games;resetStats(l);GM_STORE.save(state);}
function setFixtureMode(v){state.mode=v;makeFixtures();renderFixtures();}
function renderFixtures(){const l=currentLeague();if(!l.fixtures)l.fixtures=[];app.innerHTML=`<section class="card"><h1>📅 ${t('fixtures')}</h1><div class="toolbar"><select id="fixtureMode" onchange="setFixtureMode(this.value)"><option value="single" ${state.mode==='single'?'selected':''}>${t('single')}</option><option value="double" ${state.mode==='double'?'selected':''}>${t('double')}</option></select><select onchange="state.scoreMode=this.value;GM_AUTOSAVE.now()"><option value="countdown" ${state.scoreMode==='countdown'?'selected':''}>${t('countdown')}</option><option value="normal" ${state.scoreMode==='normal'?'selected':''}>${t('normal')}</option></select><button class="gold" onclick="makeFixtures();renderFixtures()">${t('generate')}</button></div><p class="small">${l.teams.length} ${t('team')} · ${l.fixtures.length} ${t('fixtures')}</p><div class="list">${l.fixtures.length?l.fixtures.map((g,i)=>fixtureRow(l,g,i)).join(''):`<p class="small">${t('generate')}</p>`}</div></section><section class="card"><h2>📊 ${t('table')}</h2>${tableHtml(l)}</section>`;}
function fixtureRow(l,g,i){const h=l.teams[g.h],a=l.teams[g.a];return `<div class="match"><div>${h.name}</div><div class="score">${g.played?`${g.hg}:${g.ag}`:'-:-'}</div><div>${a.name}</div><div class="center" style="grid-column:1/4"><button ${g.played?'disabled':''} onclick="startMatch(${i})">⚽ ${t('play')}</button></div></div>`;}
function startMatch(i){const l=currentLeague();const g=l.fixtures[i];if(!g)return;const h=l.teams[g.h],a=l.teams[g.a];if((h.numbers||[]).length<16||(a.numbers||[]).length<16)return alert(t('rollAll'));activeMatch={fixture:i,round:0,hg:0,ag:0,events:[]};go('play');}
function renderPlay(){const l=currentLeague();const g=l.fixtures[activeMatch.fixture];const h=l.teams[g.h],a=l.teams[g.a];app.innerHTML=`<section class="card"><h1>⚽ ${h.name} - ${a.name}</h1><div class="score">${activeMatch.hg}:${activeMatch.ag}</div><button class="gold" onclick="nextRound()">${t('next')}</button><div class="list">${activeMatch.events.map(e=>`<div class="row"><span>${e}</span></div>`).join('')}</div></section>`;}
function nextRound(){const l=currentLeague();const g=l.fixtures[activeMatch.fixture];const h=l.teams[g.h],a=l.teams[g.a];if(activeMatch.round>=16){finishMatch();return;}const r=activeMatch.round;const hn=h.numbers[r],an=a.numbers[r];let ev=`${t('round')} ${r+1}: ${hn} - ${an}`;if(hn===1||an===1||hn===an){GM_SOUNDS.draw();ev+=' 🎴';}
 if(hn>an)activeMatch.hg++;else if(an>hn)activeMatch.ag++; activeMatch.events.unshift(ev);activeMatch.round++; if(activeMatch.round>=16)finishMatch(false);else renderPlay();}
function finishMatch(goBack=true){const l=currentLeague();const g=l.fixtures[activeMatch.fixture];g.played=true;g.hg=activeMatch.hg;g.ag=activeMatch.ag;applyResult(l,g);GM_AUTOSAVE.now();const msg=`${t('finished')}: ${g.hg}:${g.ag}`;GM_SOUNDS.applause();setTimeout(()=>{alert(msg);go('fixtures');},250);}
function resetStats(l){l.teams.forEach(tm=>tm.stats={p:0,w:0,d:0,l:0,gf:0,ga:0});}
function applyResult(l,g){const h=l.teams[g.h],a=l.teams[g.a];[h,a].forEach(tm=>{tm.stats=tm.stats||{p:0,w:0,d:0,l:0,gf:0,ga:0};tm.stats.p++;});h.stats.gf+=g.hg;h.stats.ga+=g.ag;a.stats.gf+=g.ag;a.stats.ga+=g.hg;if(g.hg>g.ag){h.stats.w++;a.stats.l++;}else if(g.ag>g.hg){a.stats.w++;h.stats.l++;}else{h.stats.d++;a.stats.d++;}}
function tableHtml(l){const rows=[...l.teams].sort((a,b)=>(pts(b)-pts(a))||((b.stats.gf-b.stats.ga)-(a.stats.gf-a.stats.ga))||b.stats.gf-a.stats.gf);return `<div class="tableWrap"><table><tr><th>#</th><th>${t('team')}</th><th>P</th><th>G</th><th>U</th><th>V</th><th>T</th><th>TD</th></tr>${rows.map((tm,i)=>`<tr><td>${i+1}</td><td>${tm.name}</td><td>${pts(tm)}</td><td>${tm.stats.w}</td><td>${tm.stats.d}</td><td>${tm.stats.l}</td><td>${tm.stats.gf}:${tm.stats.ga}</td><td>${tm.stats.gf-tm.stats.ga}</td></tr>`).join('')}</table></div>`;}
function pts(tm){return (tm.stats.w||0)*3+(tm.stats.d||0);}
function renderSimpleCup(type){const list=type==='worldcup'?state.worldcup:state.champions;const title=type==='worldcup'?t('worldcup'):t('champions');const options=(type==='worldcup'?GM_DATA.worldCup:currentLeague().teams.map(x=>x.name)).filter(n=>!list.includes(n));htmlPage((type==='worldcup'?'🌍 ':'⭐ ')+title,`<div class="toolbar"><select id="cupAdd">${options.map(n=>`<option>${n}</option>`).join('')}</select><button onclick="addCup('${type}')">➕ ${t('add')}</button></div><div class="list">${list.map((n,i)=>`<div class="row"><span>${n}</span><button onclick="removeCup('${type}',${i})">${t('remove')}</button></div>`).join('')||t('noTeams')}</div>`);}
function addCup(type){const v=document.getElementById('cupAdd').value;if(!v)return;state[type].push(v);GM_STORE.save(state);renderSimpleCup(type);}
function removeCup(type,i){state[type].splice(i,1);GM_STORE.save(state);renderSimpleCup(type);}
function renderSeason(){const all=[];Object.values(state.leagues).forEach(ls=>ls.forEach(l=>l.teams.forEach(tm=>all.push(tm))));all.sort((a,b)=>pts(b)-pts(a));htmlPage('💾 '+t('seasonManager'),`<h2>Top 20</h2><div class="tableWrap"><table>${all.slice(0,20).map((tm,i)=>`<tr><td>${i+1}</td><td>${tm.name}</td><td>${pts(tm)}</td></tr>`).join('')}</table></div>`);}
function renderRecords(){htmlPage('🥇 '+t('records'),`<p class="small">GOALMONDO World V6.0</p><p>${t('applause')}</p>`);}
function manualSave(){GM_STORE.backup(state);GM_AUTOSAVE.now();alert('✅ '+t('saved'));}
function restoreBackup(){const s=GM_STORE.restore();if(s){state=s;alert('✅ '+t('restoreBackup'));render();GM_AUTOSAVE.now();}else alert('Kein Backup gefunden');}
function testSave(){try{GM_STORE.backup(state);GM_STORE.save(state);const raw=localStorage.getItem('GOALMONDO_WORLD_V6_STATE');if(!raw)throw new Error('Kein Speicherwert gefunden');const parsed=JSON.parse(raw);if(!parsed||!parsed.leagues)throw new Error('Speicherwert unvollständig');alert('✅ Speichern erfolgreich getestet');}catch(e){alert('❌ Speicher-Test fehlgeschlagen: '+e.message);}}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}

const GM_AUTOSAVE=(function(){
 let timer=null;
 let installed=false;

 function now(){
   try{return GM_STORE.save(state);}catch(e){console.error('AutoSave error',e);return false;}
 }

 function schedule(){
   clearTimeout(timer);
   timer=setTimeout(now,150);
 }

 function install(){
   if(installed) return;
   installed=true;

   ['click','change','input'].forEach(ev=>{
     document.addEventListener(ev,()=>schedule(),true);
   });

   document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')now();});
   window.addEventListener('pagehide',now);
   window.addEventListener('beforeunload',now);
   window.addEventListener('blur',now);
   setInterval(now,20000);
 }

 return {now,schedule,install};
})();

init();
